---

- name: Install rbenv
  apt:
    name: rbenv
    state: present
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - libssl-dev
    - libreadline-dev
