---

- include: prepare_for_ansible.yml

- include: upgrade_server.yml

- name: Create users
  hosts: app
  become: yes

  tasks:

    - name: create deploy user v1
      user:
        name: "{{ users.deploy.username }}"
        shell: "{{ users.deploy.shell }}"
        groups: "{{ users.deploy.groups }}"
        append: yes


- name: Configure app server
  hosts: app
  become: yes

  roles:
    - role: rbenv
      rbenv:
        ruby_version: "{{ ruby.version }}"
        deploy_user: "{{ users.deploy.username }}"
    - role: nginx_with_passenger
      passenger:
        ruby_path:  /home/{{ users.deploy.username }}/.rbenv/shims/ruby


- name: Configure db server
  hosts: db
  become: yes
  tags: db
  roles:
    - mysql

- name: Install application
  hosts: app
  become: true
  become_user: "{{ users.deploy.username }}"

  tags:
    - app2

  tasks:

    - name: Copy host configuration file to nginx
      become_user: root
      template:
        src: app.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: Restart nginx
      become_user: root
      service:
          name: nginx
          state: restarted

    - name: Clone app repository
      git:
        repo: 'https://github.com/AlvaroMaceda/DuckRecognizer.git'
        dest: "~/DuckRecognizer"
        force: yes # Because if we run the playbook again, we have had made changes in configuration files

    - name: Install dependencies for gems
      become_user: root
      apt:
        name: "{{ item }}"
      with_items:
        - libmysqlclient-dev
        - libsqlite3-dev
        # - ¿sqlite3?

    - name: Install gems with bundler
      bundler:
        state: present
        executable: /home/{{ users.deploy.username }}/.rbenv/shims/bundle
        chdir: /home/{{ users.deploy.username }}/DuckRecognizer

    - name: Create secrets file
      template:
        src: secrets.yml.j2
        dest: /home/{{ users.deploy.username }}/DuckRecognizer/config/secrets.yml

    - name: Run migration
      shell: ~/.rbenv/shims/bundle exec rake db:migrate
      args:
        chdir: /home/{{ users.deploy.username }}/DuckRecognizer
