---

# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7
- name: Add repository key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 561F9B9CAC40B2F7
    state: present

# sudo apt-get install -y apt-transport-https ca-certificates
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates

# sudo sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list'
- name: Add Passenger APT repository
  apt_repository:
    repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main
    state: present

# sudo apt-get install -y nginx-extras passenger
- name: Install Passenger & Nginx
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx-extras
    - passenger
