---

- name: Workaround for relative private keys
  hosts: all
  gather_facts: no

  tasks:
    - name: Set  correct ssh key path
      set_fact:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
      when: ansible_ssh_private_key_file is defined

- name: Prepare server to work with ansible
  hosts: all
  gather_facts: False
  become: true

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Do something in app hosts
  hosts: app
  gather_facts: no
  tags: msg1

  tasks:

    - name: Show debug info
      debug: msg=Hola

- name: Vars specification
  hosts: db
  gather_facts: no
  tags: msg2
  vars:
    v1:
      - Hola
      - Caracola
  vars_files:
     - vars.yml

  tasks:

    - name: Show v1
      debug: msg=v1:{{ v1 }}

    - name: Show v2
      debug: msg=v2:{{ v2 }}












#
