---

- name: Workaround for relative private keys
  hosts: all
  gather_facts: no

  tasks:
    - name: Set  correct ssh key path
      set_fact:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
      when: ansible_ssh_private_key_file is defined

- name: Prepare server to work with ansible
  hosts: all
  gather_facts: False
  become: true

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Upgrade server
  hosts: all
  become: true

  tasks:
    - apt:
        upgrade: dist
        update_cache: yes

- name: Create users
  hosts: all
  become: true

  tasks:

    - name: create deploy user v1
      user: name=deploy shell=/bin/bash groups=sudo append=yes
    #
    # - name: create deploy user v2
    #   user: >
    #     name=deploy
    #     shell=/bin/bash
    #     groups=sudo
    #     append=yes
    #
    # - name: create deploy user v3
    #   user:
    #     name: deploy
    #     shell: /bin/bash
    #     groups: sudo
    #     append: yes
    #
    # - name: create deploy user v4
    #   user: name=deploy shell=/bin/bash
    #   args:
    #     groups: sudo
    #     append: yes

- name: Install rbenv and build utilities
  hosts: all
  become: true

  tasks:
    - name: Update repositories cache and install rbenv
      apt:
        name: rbenv
        state: present
        update_cache: yes

    - name: Install build utilities
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev

- name: Configure rbenv
  hosts: all
  become: true
  become_user: deploy

  tags:
      - rbenv

  tasks:

    # echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    - name: Automatically init rbenv
      lineinfile:
        # path: ~/.bashrc
        dest: ~/.bashrc
        regexp: eval "\$\(rbenv init -\)"
        line: eval "$(rbenv init -)"
        insertafter: EOF

    # git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins
    - name: Install rbenv ruby-build plugin
      git:
        repo: git://github.com/sstephenson/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    # rbenv install 2.4.0
    - name: Install ruby 2.4.0
      command: /usr/bin/rbenv install 2.4.0
      args:
        creates: ~/.rbenv/versions/2.4.0

    # rbenv global 2.4.0
    - name: Make 2.4.0 global
      command: /usr/bin/rbenv global 2.4.0

    # gem install bundler
    - name: Install Bundler
      shell: eval "$(/usr/bin/rbenv init -)" && gem install bundler
      args:
        executable: /bin/bash
        creates: ~/.rbenv/versions/2.4.0/bin/bundler


    # rbenv rehash
    - name: Rehash rbenv
      command: /usr/bin/rbenv rehash


- name: Install nginx and passenger
  hosts: all
  become: true
  become_user: root
  tags: nginx

  tasks:

    - name: install apt-key docker
      apt_key: >
        keyserver="hkp://pgp.mit.edu:80"
        id="58118E89F3A912897C070ADBF76221572C52609D"

    - name: Add key
      apt_key:
        id: 561F9B9CAC40B2F7
        keyserver: "hkp://keyserver.ubuntu.com:80"
        state: present

    - name: Add repository
      apt_repository:
        repo: deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main
        state: present

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: Install nginx + passenger
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx-extras
        - passenger

- name: Configure nginx and passenger
  hosts: all
  become: true
  become_user: root

  tasks:

    - name: Include Passenger configuration in nginx
      lineinfile:
        dest: /etc/nginx/nginx.conf
        regexp: include \/etc\/nginx\/passenger\.conf;
        line: include /etc/nginx/passenger.conf;
        insertafter: EOF

    - name: Point Passenger to the version of Ruby that we're using
      lineinfile:
        dest: /etc/nginx/passenger.conf
        regexp: passenger_ruby
        line: passenger_ruby /home/deploy/.rbenv/shims/ruby;
        insertafter: EOF

    - name: Restart nginx
      service:
          name: nginx
          state: restarted

- name: Install mysql server
  hosts: all
  become: true
  become_user: root

  tags:
      - mysql

  tasks:

    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='1234' vtype='password'

    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='1234' vtype='password'

    - name: Install MySQL and mysql-python
      apt:
        name: "{{ item }}"
      with_items:
        - mysql-server
        - python-mysqldb

    - name: Start the MySQL service
      action: service name=mysql state=started

    - name: Copy host configuration file to nginx
      copy:
        src: my.cnf
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 600


- name: Configure mysql server
  hosts: all
  become: true
  become_user: root

  tags:
      - mysql

  tasks:

    - name: Create database
      mysql_db:
        name: DuckRecognizer
        state: present

    - name: Create database user
      mysql_user:
        name: duckrecognizer
        password: duckrecognizer
        priv: 'DuckRecognizer.*:ALL'
        state: present

- name: Install application
  hosts: all
  become: true
  become_user: deploy

  tasks:

    - name: Copy host configuration file to nginx
      become_user: root
      copy:
        src: app.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: Restart nginx
      become_user: root
      service:
          name: nginx
          state: restarted

    - name: Clone app repository
      git:
        repo: 'https://github.com/AlvaroMaceda/DuckRecognizer.git'
        dest: "~/DuckRecognizer"
    # https://github.com/AlvaroMaceda/DuckRecognizer.git

    - name: Install dependencies for gems
      become_user: root
      apt:
        name: "{{ item }}"
      with_items:
        - libmysqlclient-dev
        - libsqlite3-dev
        # - ¿sqlite3?

# sudo apt-get install nodejs -> uglifier ¿¿?

    - name: Install gems with bundler
      bundler:
        state: present
        executable: ~/.rbenv/shims/bundle #~/.rvm/gems/2.1.5/bin/bundle
        chdir: /home/deploy/DuckRecognizer
    #      gem_path:  # Relative to chdir
    #      bundle install --deployment --binstubs


    # - name: Create configuration file


    # - name: copy .my.cnf file with root password credentials
    #   template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
