---

- name: Workaround for relative private keys
  hosts: all
  gather_facts: no

  tasks:
    - name: Set  correct ssh key path
      set_fact:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
      when: ansible_ssh_private_key_file is defined

- name: Prepare server to work with ansible
  hosts: all
  gather_facts: False
  become: true

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Create users
  hosts: all
  become: true

  tasks:

    - name: create deploy user v1
      user: name=deploy shell=/bin/bash groups=sudo append=yes

    - name: create deploy user v2
      user: >
        name=deploy
        shell=/bin/bash
        groups=sudo
        append=yes

    - name: create deploy user v3
      user:
        name: deploy
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: create deploy user v4
      user: name=deploy shell=/bin/bash
      args:
        groups: sudo
        append: yes
