---

- name: workaround for relative private keys
  hosts: all
  gather_facts: no
  tasks:
    - name: Set  correct ssh key path
      set_fact:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
      when: ansible_ssh_private_key_file is defined

- name: show ssh key path
  hosts: all
  gather_facts: no
  tasks:
    - name: imprimir
      debug: msg="{{ ansible_ssh_private_key_file }}"

- name: test ping
  hosts: all
  gather_facts: no
  tasks:
    - name: Set  correct ssh key path
      set_fact:
        ansible_ssh_private_key_file: "{{ ansible_ssh_private_key_file | realpath }}"
      when: ansible_ssh_private_key_file is defined
    - ping:
