---

- include: prepare_for_ansible.yml

- include: upgrade_server.yml

- include: create_users.yml

- include: install_rbenv.yml

- include: configure_rbenv.yml

- include: install_nginx_and_passenger.yml

- include: configure_nginx_and_passenger.yml

- include: install_mysql_server.yml

- include: configure_mysql_server.yml

- name: Install application
  hosts: app
  become: true
  become_user: "{{ users.deploy.username }}"

  tags:
    - app

  tasks:

    - name: Copy host configuration file to nginx
      become_user: root
      template:
        src: app.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"

    - name: Restart nginx
      become_user: root
      service:
          name: nginx
          state: restarted

    - name: Clone app repository
      git:
        repo: 'https://github.com/AlvaroMaceda/DuckRecognizer.git'
        dest: "~/DuckRecognizer"
        force: yes # Because if we run the playbook again, we have had made changes in configuration files

    - name: Install dependencies for gems
      become_user: root
      apt:
        name: "{{ item }}"
      with_items:
        - libmysqlclient-dev
        - libsqlite3-dev
        # - ¿sqlite3?

    - name: Install gems with bundler
      bundler:
        state: present
        executable: ~/.rbenv/shims/bundle
        chdir: /home/{{ users.deploy.username }}/DuckRecognizer

    - name: Create secrets file
      template:
        src: secrets.yml.j2
        dest: /home/{{ users.deploy.username }}/DuckRecognizer/config/secrets.yml

    - name: Run migration
      shell: ~/.rbenv/shims/bundle exec rake db:migrate
      args:
        chdir: /home/{{ users.deploy.username }}/DuckRecognizer
