---

  users:
    deploy:
      username: deploy
      shell: /bin/bash
      groups: sudo

  ruby:
    version: 2.4.0

  rails:
    environment: development

  # rbenv:
  #   ruby_version: "{{ ruby.version }}"
  #   deploy_user: "{{ users.deploy.username }}"
